sudo: false
language: cpp

git:
  submodules:
    true

os: linux
dist: xenial

addons:
  apt:
    update: true
    packages:
      - lcov          # Code Coverage
      - valgrind      # Memory Leaks

script:
  # Building
  - mkdir -p build && cd build
  - cmake -DCODE_COVERAGE=ON ..
  - cmake --build . 
  # Tests (with valgrind)
  - valgrind --leak-check=full --show-leak-kinds=all ./Hello --gtest_output="xml:../doc/GoogleTestReport.xml"
  # Code Coverage
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'googletest/*' '/usr/include/*' '/usr/lib/*' -o coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

notifications:
  email: false
